- hosts: NYC1

  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes

    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
      become: yes
